<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CloudinaryDotNet" Version="1.27.4" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="8.0.13" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.13" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.13" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.13" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.14" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.13" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.13">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WorkNestify.DataAccess\WorkNestify.DataAccess.csproj" />
      <ProjectReference Include="..\WorkNestify.Models\WorkNestify.Models.csproj" />
      <ProjectReference Include="..\WorkNestify.Services\WorkNestify.Services.csproj" />
      <ProjectReference Include="..\WorkNestify.Utilities\WorkNestify.Utilities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Areas\JobSeeker\Views\Home\Index.cshtml" />
      <AdditionalFiles Include="Areas\JobSeeker\Views\Home\Privacy.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Employer\Controllers\" />
      <Folder Include="wwwroot\assets\images\" />
      <Folder Include="wwwroot\css\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanyReview\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanyReview\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanyReview\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanyReview\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanyReview\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanySize\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CompanySize\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobApplicationStatus\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobApplicationStatus\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobLevel\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobLevel\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobStatus\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobStatus\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobType\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\JobType\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Employer\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Employer\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Employer\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Employer\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\Employer\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\AccessDenied.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ConfirmEmail.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ExternalLogin.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ForgotPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Lockout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Login.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\LoginWith2fa.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Logout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\Email.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\PersonalData.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\SetPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_StatusMessage.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Register.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\RegisterConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ResendEmailConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ResetPassword.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\_StatusMessage.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\bootstrap\LICENSE" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\buttons.bootstrap5.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\buttons.bootstrap5.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\buttons.bootstrap5.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\buttons.bootstrap5.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.bootstrap5.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.bootstrap5.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.bootstrap5.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.bootstrap5.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.responsive.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\dataTables.responsive.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\js\buttons.html5.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\js\buttons.html5.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\js\buttons.print.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\js\buttons.print.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\js\dataTables.buttons.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\js\dataTables.buttons.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\responsive.bootstrap5.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\responsive.bootstrap5.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\responsive.bootstrap5.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\datatables\responsive.bootstrap5.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\additional-methods.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation\LICENSE.md" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jszip\jszip.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jszip\jszip.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\pdfmake\pdfmake.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\pdfmake\pdfmake.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\pdfmake\vfs_fonts.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\pdfmake\vfs_fonts.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\animate.css\animate.min.css" />
      <_ContentIncludedByDefault Remove="Areas\Employer\Views\Job\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Employer\Views\Job\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Employer\Views\Job\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Employer\Views\Job\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Employer\Views\Job\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\AccessDenied.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ConfirmEmail.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ExternalLogin.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ForgotPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Lockout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Login.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\LoginWith2fa.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Logout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Email.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Index.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\PersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\SetPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_Layout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_StatusMessage.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Register.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\RegisterConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResendEmailConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResetPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_StatusMessage.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ValidationScriptsPartial.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\AccessDenied.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ConfirmEmail.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ExternalLogin.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ForgotPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Lockout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Login.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\LoginWith2fa.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Logout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Email.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Index.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\PersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\SetPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_Layout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_StatusMessage.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Register.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\RegisterConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResendEmailConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResetPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_StatusMessage.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ValidationScriptsPartial.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\AccessDenied.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ConfirmEmail.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ExternalLogin.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ForgotPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Lockout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Login.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\LoginWith2fa.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Logout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Email.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\Index.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\PersonalData.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\SetPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_Layout.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_ManageNav.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_StatusMessage.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Manage\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\Register.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\RegisterConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResendEmailConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResetPassword.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_StatusMessage.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\Account\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ValidationScriptsPartial.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewImports.cshtml" />
      <UpToDateCheckInput Remove="Areas\Identity\Pages\_ViewStart.cshtml" />
    </ItemGroup>

</Project>
