using WorkNestify.Models.Models.Jobs;
using WorkNestify.Utilities.Constants;

namespace WorkNestify.DataAccess.DbInitializer.Seeds;

public static class JobSeed
{
    public static List<Job> GetJobs()
    {
        var now = DateTime.UtcNow;
        return new List<Job>
        {
            new Job { Title = "Senior Software Engineer", CompanyId = 1, ProvinceCode = 1, WardCode = 181, Salary = 35000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FPT Core dev.", StreetAddress = "10 Pham Van Bach" },
            new Job { Title = "Digital Marketing Specialist", CompanyId = 2, ProvinceCode = 1, WardCode = 331, Salary = 20000000, JobCategoryId = 2, Level = JobLevels.Junior, Type = JobTypes.Freelance, CreatedDate = now, Status = JobStatuses.Open, Description = "SEO SEM Base.", StreetAddress = "123 Nguyen Trai" },
            new Job { Title = "Sales Representative", CompanyId = 3, ProvinceCode = 79, WardCode = 27040, Salary = 15000000, JobCategoryId = 3, Level = JobLevels.Fresher, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "KiotViet POS.", StreetAddress = "10 Pho Quang" },
            new Job { Title = "Barista", CompanyId = 4, ProvinceCode = 79, WardCode = 26845, Salary = 8000000, JobCategoryId = 9, Level = JobLevels.Intern, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Barista TCH.", StreetAddress = "86 Cao Thang" },
            new Job { Title = "Financial Analyst", CompanyId = 7, ProvinceCode = 1, WardCode = 103, Salary = 25000000, JobCategoryId = 5, Level = JobLevels.Junior, Type = JobTypes.Remote, CreatedDate = now, Status = JobStatuses.Open, Description = "Techcom analyst.", StreetAddress = "6 Quang Trung" },
            new Job { Title = "HR Intern", CompanyId = 8, ProvinceCode = 1, WardCode = 277, Salary = 5000000, JobCategoryId = 6, Level = JobLevels.Intern, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "VinFast HR.", StreetAddress = "Riverside Long Bien" },
            new Job { Title = "Mechanical Engineer", CompanyId = 9, ProvinceCode = 1, WardCode = 49, Salary = 28000000, JobCategoryId = 7, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Shopee Eng.", StreetAddress = "29 Lieu Giai" },
            new Job { Title = "Game Developer", CompanyId = 10, ProvinceCode = 79, WardCode = 27265, Salary = 30000000, JobCategoryId = 1, Level = JobLevels.Junior, Type = JobTypes.Remote, CreatedDate = now, Status = JobStatuses.Open, Description = "VNG Unity.", StreetAddress = "Tan Thuan Dong" },
            new Job { Title = "Supply Chain Coordinator", CompanyId = 15, ProvinceCode = 79, WardCode = 26734, Salary = 22000000, JobCategoryId = 10, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Lazada Logi.", StreetAddress = "Saigon Centre" },
            new Job { Title = "Software Development Intern", CompanyId = 17, ProvinceCode = 48, WardCode = 20197, Salary = 4000000, JobCategoryId = 1, Level = JobLevels.Intern, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Axon React.", StreetAddress = "30/4 Street" },
            new Job { Title = "IT Support Specialist", CompanyId = 1, ProvinceCode = 1, WardCode = 181, Salary = 18000000, JobCategoryId = 1, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FPT Tech supp.", StreetAddress = "FPT Tower" },
            new Job { Title = "SEO Freelancer", CompanyId = 2, ProvinceCode = 1, WardCode = 331, Salary = 12000000, JobCategoryId = 2, Level = JobLevels.Fresher, Type = JobTypes.Freelance, CreatedDate = now, Status = JobStatuses.Open, Description = "Base SEO.", StreetAddress = "123 Nguyen Trai" },
            new Job { Title = "Sales Intern", CompanyId = 3, ProvinceCode = 79, WardCode = 27040, Salary = 3000000, JobCategoryId = 3, Level = JobLevels.Intern, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Kiot Sales.", StreetAddress = "Pho Quang" },
            new Job { Title = "Customer Service Representative", CompanyId = 4, ProvinceCode = 79, WardCode = 26845, Salary = 10000000, JobCategoryId = 9, Level = JobLevels.Fresher, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "TCH CS.", StreetAddress = "Cao Thang" },
            new Job { Title = "Accountant", CompanyId = 7, ProvinceCode = 1, WardCode = 103, Salary = 20000000, JobCategoryId = 5, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "TCB Accounting.", StreetAddress = "6 Quang Trung" },
            new Job { JobCategoryId = 6, Title = "Recruitment Specialist", CompanyId = 8, ProvinceCode = 1, WardCode = 277, Salary = 22000000, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "VinFast Recruitment.", StreetAddress = "Riverside" },
            new Job { Title = "Electrical Engineer", CompanyId = 9, ProvinceCode = 1, WardCode = 49, Salary = 27000000, JobCategoryId = 7, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Shopee Elec.", StreetAddress = "Lieu Giai" },
            new Job { Title = "Mobile App Developer", CompanyId = 10, ProvinceCode = 79, WardCode = 27265, Salary = 28000000, JobCategoryId = 1, Level = JobLevels.Junior, Type = JobTypes.Remote, CreatedDate = now, Status = JobStatuses.Open, Description = "VNG App.", StreetAddress = "Z06" },
            new Job { Title = "Logistics Manager", CompanyId = 15, ProvinceCode = 79, WardCode = 26734, Salary = 35000000, JobCategoryId = 10, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Lazada Mng.", StreetAddress = "Le Loi" },
            new Job { Title = "Web Developer", CompanyId = 17, ProvinceCode = 48, WardCode = 20197, Salary = 20000000, JobCategoryId = 1, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Axon Web.", StreetAddress = "PVcomBank" },
            new Job { Title = "Content Creator", CompanyId = 5, ProvinceCode = 79, WardCode = 26758, Salary = 15000000, JobCategoryId = 2, Level = JobLevels.Fresher, Type = JobTypes.Freelance, CreatedDate = now, Status = JobStatuses.Open, Description = "Foody Content.", StreetAddress = "Cong Quynh" },
            new Job { Title = "Product Manager", CompanyId = 6, ProvinceCode = 1, WardCode = 208, Salary = 32000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Digiworld PM.", StreetAddress = "TNR Tower" },
            new Job { Title = "Training Coordinator", CompanyId = 11, ProvinceCode = 79, WardCode = 26734, Salary = 18000000, JobCategoryId = 8, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Sun Training.", StreetAddress = "Le Loi" },
            new Job { Title = "Café Manager", CompanyId = 12, ProvinceCode = 1, WardCode = 103, Salary = 25000000, JobCategoryId = 9, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Highlands Mng.", StreetAddress = "Tran Quang Khai" },
            new Job { Title = "Network Engineer", CompanyId = 13, ProvinceCode = 1, WardCode = 181, Salary = 30000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Viettel Net.", StreetAddress = "Cau Giay" },
            new Job { Title = "Real Estate Agent", CompanyId = 14, ProvinceCode = 1, WardCode = 403, Salary = 20000000, JobCategoryId = 3, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FLC Sales.", StreetAddress = "My Dinh" },
            new Job { Title = "Delivery Coordinator", CompanyId = 16, ProvinceCode = 79, WardCode = 27046, Salary = 18000000, JobCategoryId = 10, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Tiki Coord.", StreetAddress = "Ut Tich" },
            new Job { Title = "Marketing Intern", CompanyId = 18, ProvinceCode = 79, WardCode = 26734, Salary = 4000000, JobCategoryId = 2, Level = JobLevels.Intern, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Phuc Long Mkt.", StreetAddress = "Le Duan" },
            new Job { Title = "Cloud Engineer", CompanyId = 1, ProvinceCode = 1, WardCode = 181, Salary = 32000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FPT Cloud.", StreetAddress = "Pham Van Bach" },
            new Job { Title = "Sales Manager", CompanyId = 3, ProvinceCode = 79, WardCode = 27040, Salary = 30000000, JobCategoryId = 3, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Kiot Mng.", StreetAddress = "Pho Quang" },
            new Job { Title = "Cashier", CompanyId = 4, ProvinceCode = 79, WardCode = 26845, Salary = 9000000, JobCategoryId = 9, Level = JobLevels.Fresher, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "TCH Cashier.", StreetAddress = "Cao Thang" },
            new Job { Title = "Bank Teller", CompanyId = 7, ProvinceCode = 1, WardCode = 103, Salary = 12000000, JobCategoryId = 5, Level = JobLevels.Fresher, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "TCB Teller.", StreetAddress = "Quang Trung" },
            new Job { Title = "UI/UX Designer", CompanyId = 10, ProvinceCode = 79, WardCode = 27265, Salary = 25000000, JobCategoryId = 1, Level = JobLevels.Junior, Type = JobTypes.Remote, CreatedDate = now, Status = JobStatuses.Open, Description = "VNG UIUX.", StreetAddress = "13 Street" },
            new Job { Title = "Warehouse Supervisor", CompanyId = 15, ProvinceCode = 79, WardCode = 26734, Salary = 20000000, JobCategoryId = 10, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Lazada WH.", StreetAddress = "Le Loi" },
            new Job { Title = "QA Engineer", CompanyId = 17, ProvinceCode = 48, WardCode = 20197, Salary = 18000000, JobCategoryId = 1, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Axon QA.", StreetAddress = "30/4" },
            new Job { Title = "Social Media Manager", CompanyId = 5, ProvinceCode = 79, WardCode = 26758, Salary = 22000000, JobCategoryId = 2, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Foody Media.", StreetAddress = "Cong Quynh" },
            new Job { Title = "Distribution Specialist", CompanyId = 6, ProvinceCode = 1, WardCode = 208, Salary = 20000000, JobCategoryId = 10, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "DGW Dist.", StreetAddress = "Nguyen Chi Thanh" },
            new Job { Title = "Trainer", CompanyId = 11, ProvinceCode = 79, WardCode = 26734, Salary = 20000000, JobCategoryId = 8, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Sun Trainer.", StreetAddress = "Bến Nghé" },
            new Job { Title = "Barista Supervisor", CompanyId = 12, ProvinceCode = 1, WardCode = 103, Salary = 15000000, JobCategoryId = 9, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Highlands Super.", StreetAddress = "Hoan Kiem" },
            new Job { Title = "Cybersecurity Specialist", CompanyId = 13, ProvinceCode = 1, WardCode = 181, Salary = 35000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Viettel Cyber.", StreetAddress = "Cau Giay" },
            new Job { Title = "Property Manager", CompanyId = 14, ProvinceCode = 1, WardCode = 403, Salary = 25000000, JobCategoryId = 3, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FLC Manager.", StreetAddress = "My Dinh" },
            new Job { Title = "Logistics Intern", CompanyId = 16, ProvinceCode = 79, WardCode = 27046, Salary = 3000000, JobCategoryId = 10, Level = JobLevels.Intern, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Tiki Intern.", StreetAddress = "Ut Tich" },
            new Job { Title = "Tea Specialist", CompanyId = 18, ProvinceCode = 79, WardCode = 26734, Salary = 10000000, JobCategoryId = 9, Level = JobLevels.Fresher, Type = JobTypes.PartTime, CreatedDate = now, Status = JobStatuses.Open, Description = "PL Specialist.", StreetAddress = "Ben Nghe" },
            new Job { Title = "DevOps Engineer", CompanyId = 1, ProvinceCode = 1, WardCode = 181, Salary = 33000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FPT DevOps.", StreetAddress = "Cau Giay" },
            new Job { Title = "Marketing Manager", CompanyId = 2, ProvinceCode = 1, WardCode = 331, Salary = 35000000, JobCategoryId = 2, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Base Mng.", StreetAddress = "Thanh Xuan" },
            new Job { Title = "Sales Consultant", CompanyId = 3, ProvinceCode = 79, WardCode = 27040, Salary = 18000000, JobCategoryId = 3, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "Kiot Consultant.", StreetAddress = "Tan Binh" },
            new Job { Title = "Customer Support Lead", CompanyId = 4, ProvinceCode = 79, WardCode = 26845, Salary = 20000000, JobCategoryId = 9, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "TCH Support Lead.", StreetAddress = "Quan 3" },
            new Job { Title = "Investment Analyst", CompanyId = 7, ProvinceCode = 1, WardCode = 103, Salary = 28000000, JobCategoryId = 5, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "TCB Invest.", StreetAddress = "Quang Trung" },
            new Job { Title = "Office Administrator", CompanyId = 6, ProvinceCode = 1, WardCode = 208, Salary = 15000000, JobCategoryId = 8, Level = JobLevels.Junior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "DGW Admin.", StreetAddress = "Nguyen Chi Thanh" },
            new Job { Title = "Java Tech Lead", CompanyId = 1, ProvinceCode = 1, WardCode = 181, Salary = 45000000, JobCategoryId = 1, Level = JobLevels.Senior, Type = JobTypes.FullTime, CreatedDate = now, Status = JobStatuses.Open, Description = "FPT Tech Lead.", StreetAddress = "Dich Vong Hau" }
        };
    }
}